[".nvm"]
type = "git-repo"
url = "https://github.com/nvm-sh/nvm.git"
refreshPeriod = "168h"
clone.args = ["--depth=1"]

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"
clone.args = ["--depth=1"]

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"
clone.args = ["--depth=1"]

[".tmux"]
type = "git-repo"
url = "https://github.com/gpakosz/.tmux.git"
refreshPeriod = "168h"
clone.args = ["--depth=1"]

# XDG Base Directory compliance
# Remap dot_files to ~/.config/ structure
[".zshrc"]
type = "file"
target = ".config/zsh/.zshrc"

[".zshenv"]
type = "file"
target = ".config/zsh/.zshenv"

[".config/zsh"]
type = "dir"
target = ".config/zsh"
